<a href="https://colab.research.google.com/github/Rabbi1067/DL/blob/main/Copy_of_Predict_Potato_Price_using_ANN_13_09_22_(3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [76]:
# import library and module
import tensorflow as tf
from tensorflow import keras
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [77]:
from google.colab import files
uploaded = files.upload()

Saving PotatoPrice - PotatoPrice.csv to PotatoPrice - PotatoPrice (6).csv

In [78]:
df = pd.read_csv('PotatoPrice - PotatoPrice.csv')

In [79]:
X = df[['potato_kg']]  #since x have to be two dimentional or 2D array. So [[]]
Y = df['price']

In [80]:
X

   potato_kg
0          1
1          2
2          3
3          4
4          5
5          6
6          7
7          8
8          9
9         10

In [81]:
# Split Dataset for Train and Test
from sklearn.model_selection import train_test_split

X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.3)
# X_train

In [82]:
X_train

   potato_kg
1          2
5          6
3          4
8          9
2          3
6          7
7          8

In [83]:
# ANN Model Building
'''
model = tf.keras.Sequential([
      tf.keras.layers.Dense(1,input_shape=[1],activation='linear')
])

# model.summary()'''
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu', input_shape=[1]),
    tf.keras.layers.Dense(1)
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [87]:
# Compile The ANN model
'''model.compile(optimizer='sgd', #adam-weight update kore
              loss='mean_squared_error',
             metrics=['accuracy'])'''
model.compile(optimizer='adam', loss='mse', metrics=['mae'])

In [88]:
#Train ANN Model
model.fit(X_train,Y_train,epochs=500)

Epoch 1/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 1s 831ms/step - loss: 5568.9399 - mae: 65.9093
Epoch 2/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5566.8682 - mae: 65.8961
Epoch 3/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 5564.7935 - mae: 65.8829
Epoch 4/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 5562.7144 - mae: 65.8698
Epoch 5/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5560.6313 - mae: 65.8565
Epoch 6/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5558.5444 - mae: 65.8433
Epoch 7/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5556.4536 - mae: 65.8300
Epoch 8/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5554.3579 - mae: 65.8167
Epoch 9/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5552.2588 - mae: 65.8033
Epoch 10/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5550.1558 - mae: 65.7900
Epoch 11/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 5548.0469 - mae: 65.7766
Epoch 12/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5545.9336 - mae: 65.7631
Epoch 13/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 5543.8164 - mae: 65.7497
Epoch 14/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 5541.6948 - mae: 65.7362
Epoch 15/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5539.5679 - mae: 65.7226
Epoch 16/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5537.4365 - mae: 65.7091
Epoch 17/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5535.2993 - mae: 65.6955
Epoch 18/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5533.1572 - mae: 65.6818
Epoch 19/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5531.0107 - mae: 65.6682
Epoch 20/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5528.8584 - mae: 65.6545
Epoch 21/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5526.7017 - mae: 65.6407
Epoch 22/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step - loss: 5524.5381 - mae: 65.6270
Epoch 23/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5522.3701 - mae: 65.6131
Epoch 24/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5520.1953 - mae: 65.5993
Epoch 25/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 5518.0156 - mae: 65.5854
Epoch 26/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 5515.8296 - mae: 65.5715
Epoch 27/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5513.6377 - mae: 65.5575
Epoch 28/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5511.4404 - mae: 65.5435
Epoch 29/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5509.2368 - mae: 65.5294
Epoch 30/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5507.0264 - mae: 65.5153
Epoch 31/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5504.8101 - mae: 65.5012
Epoch 32/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5502.5869 - mae: 65.4870
Epoch 33/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 5500.3579 - mae: 65.4727
Epoch 34/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5498.1216 - mae: 65.4585
Epoch 35/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 5495.8784 - mae: 65.4441
Epoch 36/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5493.6289 - mae: 65.4298
Epoch 37/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5491.3726 - mae: 65.4154
Epoch 38/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5489.1089 - mae: 65.4009
Epoch 39/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5486.8374 - mae: 65.3864
Epoch 40/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5484.5596 - mae: 65.3718
Epoch 41/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5482.2744 - mae: 65.3572
Epoch 42/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 5479.9810 - mae: 65.3425
Epoch 43/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5477.6807 - mae: 65.3278
Epoch 44/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 5475.3726 - mae: 65.3131
Epoch 45/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5473.0571 - mae: 65.2982
Epoch 46/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 5470.7334 - mae: 65.2834
Epoch 47/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5468.4014 - mae: 65.2684
Epoch 48/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5466.0615 - mae: 65.2535
Epoch 49/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 5463.7134 - mae: 65.2384
Epoch 50/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5461.3564 - mae: 65.2233
Epoch 51/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5458.9922 - mae: 65.2082
Epoch 52/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 5456.6187 - mae: 65.1930
Epoch 53/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 45ms/step - loss: 5454.2378 - mae: 65.1777
Epoch 54/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5451.8481 - mae: 65.1624
Epoch 55/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5449.4482 - mae: 65.1470
Epoch 56/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5447.0405 - mae: 65.1315
Epoch 57/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5444.6245 - mae: 65.1160
Epoch 58/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5442.1982 - mae: 65.1005
Epoch 59/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5439.7627 - mae: 65.0848
Epoch 60/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5437.3179 - mae: 65.0691
Epoch 61/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 5434.8638 - mae: 65.0534
Epoch 62/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 5432.4014 - mae: 65.0376
Epoch 63/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5429.9282 - mae: 65.0217
Epoch 64/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5427.4453 - mae: 65.0057
Epoch 65/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5424.9531 - mae: 64.9897
Epoch 66/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 5422.4497 - mae: 64.9736
Epoch 67/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5419.9375 - mae: 64.9575
Epoch 68/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5417.4150 - mae: 64.9412
Epoch 69/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5414.8823 - mae: 64.9249
Epoch 70/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5412.3389 - mae: 64.9086
Epoch 71/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 5409.7852 - mae: 64.8921
Epoch 72/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5407.2212 - mae: 64.8756
Epoch 73/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5404.6460 - mae: 64.8591
Epoch 74/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5402.0596 - mae: 64.8424
Epoch 75/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5399.4624 - mae: 64.8257
Epoch 76/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5396.8550 - mae: 64.8089
Epoch 77/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5394.2354 - mae: 64.7920
Epoch 78/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5391.6055 - mae: 64.7750
Epoch 79/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 5388.9644 - mae: 64.7580
Epoch 80/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5386.3101 - mae: 64.7409
Epoch 81/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5383.6455 - mae: 64.7237
Epoch 82/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 5380.9688 - mae: 64.7064
Epoch 83/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5378.2803 - mae: 64.6891
Epoch 84/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5375.5796 - mae: 64.6716
Epoch 85/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5372.8672 - mae: 64.6541
Epoch 86/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 5370.1421 - mae: 64.6365
Epoch 87/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5367.4053 - mae: 64.6188
Epoch 88/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5364.6553 - mae: 64.6011
Epoch 89/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5361.8931 - mae: 64.5832
Epoch 90/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5359.1182 - mae: 64.5653
Epoch 91/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5356.3296 - mae: 64.5472
Epoch 92/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 46ms/step - loss: 5353.5288 - mae: 64.5291
Epoch 93/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5350.7148 - mae: 64.5109
Epoch 94/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 44ms/step - loss: 5347.8877 - mae: 64.4926
Epoch 95/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5345.0474 - mae: 64.4742
Epoch 96/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5342.1938 - mae: 64.4558
Epoch 97/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5339.3257 - mae: 64.4372
Epoch 98/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5336.4458 - mae: 64.4185
Epoch 99/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5333.5503 - mae: 64.3998
Epoch 100/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5330.6416 - mae: 64.3809
Epoch 101/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5327.7188 - mae: 64.3620
Epoch 102/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 5324.7822 - mae: 64.3429
Epoch 103/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5321.8315 - mae: 64.3238
Epoch 104/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5318.8662 - mae: 64.3045
Epoch 105/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 5315.8857 - mae: 64.2852
Epoch 106/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 5312.8911 - mae: 64.2658
Epoch 107/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5309.8823 - mae: 64.2462
Epoch 108/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5306.8584 - mae: 64.2266
Epoch 109/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5303.8198 - mae: 64.2068
Epoch 110/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5300.7661 - mae: 64.1870
Epoch 111/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5297.6968 - mae: 64.1670
Epoch 112/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5294.6138 - mae: 64.1470
Epoch 113/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5291.5142 - mae: 64.1268
Epoch 114/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5288.3994 - mae: 64.1065
Epoch 115/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5285.2690 - mae: 64.0862
Epoch 116/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5282.1240 - mae: 64.0657
Epoch 117/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5278.9619 - mae: 64.0451
Epoch 118/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5275.7852 - mae: 64.0244
Epoch 119/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5272.5928 - mae: 64.0036
Epoch 120/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 5269.3833 - mae: 63.9827
Epoch 121/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step - loss: 5266.1587 - mae: 63.9617
Epoch 122/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5262.9185 - mae: 63.9405
Epoch 123/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5259.6606 - mae: 63.9193
Epoch 124/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 5256.3872 - mae: 63.8979
Epoch 125/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 5253.0981 - mae: 63.8764
Epoch 126/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5249.7925 - mae: 63.8549
Epoch 127/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 5246.4702 - mae: 63.8332
Epoch 128/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5243.1313 - mae: 63.8113
Epoch 129/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5239.7759 - mae: 63.7894
Epoch 130/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5236.4038 - mae: 63.7674
Epoch 131/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 47ms/step - loss: 5233.0156 - mae: 63.7452
Epoch 132/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5229.6104 - mae: 63.7229
Epoch 133/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5226.1875 - mae: 63.7005
Epoch 134/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5222.7476 - mae: 63.6780
Epoch 135/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5219.2925 - mae: 63.6554
Epoch 136/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5215.8193 - mae: 63.6326
Epoch 137/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5212.3291 - mae: 63.6098
Epoch 138/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5208.8228 - mae: 63.5868
Epoch 139/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 5205.2979 - mae: 63.5637
Epoch 140/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step - loss: 5201.7568 - mae: 63.5404
Epoch 141/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5198.1987 - mae: 63.5171
Epoch 142/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 5194.6226 - mae: 63.4936
Epoch 143/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5191.0298 - mae: 63.4700
Epoch 144/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 5187.4189 - mae: 63.4463
Epoch 145/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5183.7915 - mae: 63.4225
Epoch 146/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5180.1470 - mae: 63.3985
Epoch 147/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5176.4844 - mae: 63.3745
Epoch 148/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5172.8052 - mae: 63.3503
Epoch 149/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5169.1079 - mae: 63.3259
Epoch 150/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 5165.3936 - mae: 63.3015
Epoch 151/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5161.6611 - mae: 63.2769
Epoch 152/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5157.9116 - mae: 63.2522
Epoch 153/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5154.1450 - mae: 63.2274
Epoch 154/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5150.3599 - mae: 63.2024
Epoch 155/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 5146.5591 - mae: 63.1774
Epoch 156/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5142.7393 - mae: 63.1522
Epoch 157/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5138.9019 - mae: 63.1269
Epoch 158/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 5135.0474 - mae: 63.1014
Epoch 159/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 85ms/step - loss: 5131.1753 - mae: 63.0759
Epoch 160/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 5127.2856 - mae: 63.0502
Epoch 161/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 5123.3789 - mae: 63.0243
Epoch 162/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 5119.4541 - mae: 62.9984
Epoch 163/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 5115.5117 - mae: 62.9723
Epoch 164/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step - loss: 5111.5522 - mae: 62.9461
Epoch 165/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 5107.5747 - mae: 62.9198
Epoch 166/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 5103.5806 - mae: 62.8933
Epoch 167/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 5099.5679 - mae: 62.8668
Epoch 168/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 5095.5391 - mae: 62.8401
Epoch 169/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 5091.4912 - mae: 62.8132
Epoch 170/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 48ms/step - loss: 5087.4268 - mae: 62.7863
Epoch 171/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 5083.3447 - mae: 62.7592
Epoch 172/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step - loss: 5079.2456 - mae: 62.7320
Epoch 173/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step - loss: 5075.1289 - mae: 62.7047
Epoch 174/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 99ms/step - loss: 5070.9946 - mae: 62.6772
Epoch 175/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 89ms/step - loss: 5066.8428 - mae: 62.6496
Epoch 176/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 5062.6743 - mae: 62.6219
Epoch 177/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 5058.4868 - mae: 62.5940
Epoch 178/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - loss: 5054.2842 - mae: 62.5661
Epoch 179/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step - loss: 5050.0630 - mae: 62.5380
Epoch 180/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 146ms/step - loss: 5045.8247 - mae: 62.5098
Epoch 181/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 5041.5693 - mae: 62.4814
Epoch 182/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 5037.2974 - mae: 62.4529
Epoch 183/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - loss: 5033.0068 - mae: 62.4243
Epoch 184/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 155ms/step - loss: 5028.7002 - mae: 62.3956
Epoch 185/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 77ms/step - loss: 5024.3774 - mae: 62.3667
Epoch 186/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - loss: 5020.0352 - mae: 62.3377
Epoch 187/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - loss: 5015.6772 - mae: 62.3086
Epoch 188/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 5011.3032 - mae: 62.2794
Epoch 189/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step - loss: 5006.9106 - mae: 62.2500
Epoch 190/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - loss: 5002.5010 - mae: 62.2206
Epoch 191/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 137ms/step - loss: 4998.0752 - mae: 62.1909
Epoch 192/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 160ms/step - loss: 4993.6333 - mae: 62.1612
Epoch 193/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 90ms/step - loss: 4989.1733 - mae: 62.1313
Epoch 194/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 88ms/step - loss: 4984.6978 - mae: 62.1013
Epoch 195/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 79ms/step - loss: 4980.2041 - mae: 62.0712
Epoch 196/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - loss: 4975.6948 - mae: 62.0410
Epoch 197/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 147ms/step - loss: 4971.1680 - mae: 62.0106
Epoch 198/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 4966.6250 - mae: 61.9801
Epoch 199/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 4962.0659 - mae: 61.9495
Epoch 200/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 4957.4893 - mae: 61.9187
Epoch 201/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 4952.8960 - mae: 61.8878
Epoch 202/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 4948.2876 - mae: 61.8568
Epoch 203/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 4943.6616 - mae: 61.8257
Epoch 204/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 4939.0200 - mae: 61.7945
Epoch 205/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 4934.3618 - mae: 61.7631
Epoch 206/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step - loss: 4929.6865 - mae: 61.7316
Epoch 207/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 4924.9961 - mae: 61.7000
Epoch 208/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 4920.2896 - mae: 61.6682
Epoch 209/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step - loss: 4915.5659 - mae: 61.6363
Epoch 210/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 4910.8271 - mae: 61.6044
Epoch 211/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 4906.0713 - mae: 61.5722
Epoch 212/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 4901.3003 - mae: 61.5400
Epoch 213/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 4896.5127 - mae: 61.5076
Epoch 214/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 4891.7100 - mae: 61.4751
Epoch 215/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 4886.8906 - mae: 61.4425
Epoch 216/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 4882.0557 - mae: 61.4098
Epoch 217/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 4877.2056 - mae: 61.3769
Epoch 218/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 4872.3389 - mae: 61.3439
Epoch 219/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 4867.4570 - mae: 61.3108
Epoch 220/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 4862.5586 - mae: 61.2776
Epoch 221/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 54ms/step - loss: 4857.6460 - mae: 61.2442
Epoch 222/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step - loss: 4852.7178 - mae: 61.2107
Epoch 223/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 4847.7729 - mae: 61.1771
Epoch 224/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step - loss: 4842.8130 - mae: 61.1434
Epoch 225/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 4837.8384 - mae: 61.1096
Epoch 226/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 50ms/step - loss: 4832.8481 - mae: 61.0756
Epoch 227/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - loss: 4827.8423 - mae: 61.0415
Epoch 228/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 4822.8213 - mae: 61.0073
Epoch 229/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 49ms/step - loss: 4817.7856 - mae: 60.9729
Epoch 230/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 55ms/step - loss: 4812.7344 - mae: 60.9385
Epoch 231/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 52ms/step - loss: 4807.6685 - mae: 60.9039
Epoch 232/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 4802.5874 - mae: 60.8692
Epoch 233/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step - loss: 4797.4912 - mae: 60.8344
Epoch 234/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 59ms/step - loss: 4792.3799 - mae: 60.7995
Epoch 235/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 53ms/step - loss: 4787.2544 - mae: 60.7644
Epoch 236/500
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 51ms/step - loss: 4782.1133 - mae: 60.7292
Epoch 237/500

In [89]:
X_test

   potato_kg
0          1
4          5
9         10

In [ ]:
#Predict
model.predict(X_test)
# X_test

In [98]:
#Predict The Output Manually
model.predict(np.array([[4]]))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 40ms/step

array([[14.156583]], dtype=float32)